- name: Create containter
  hosts: fw-docker
  tasks:
  - name: web container
    docker_container:
      name: web
      image: webimage
      state: started
      ports:
      - "8080:80"
      tty: true
      detach: true

